#!/bin/bash

usage() {
  echo "$0 /path/to/push/to"
  exit 1
}

[ $# -lt 2 ] || usage

RSYNC=$(which rsync)
if [ -z "${RSYNC}" ] ; then
  echo "Rsync not found in path. apt-get install rsync?"
  exit 2
fi

rsync -rv --checksum --exclude .git --exclude push . "$1"
